version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
    volumes:
      - ./db:/var/lib/postgresql/data
  client:
    image: "node:9"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/:/home/node/app
    ports:
      - "80:3000"
    command: bash -c "yarn && yarn start"
  server:
    build: ./server/
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/:/home/node/app
    ports:
      - "3000:3000"
    command: bash -c "yarn && nodemon ./ --config ./nodeamon.json"
    depends_on:
      - db
