version: "3.7"

services:
  db:
    image: postgres:latest
    container_name: nicoreader-db
    volumes:
      - data:/var/lib/postgresql/data
    env_file: ./.env.local
    ports:
      - "58278:5432"
volumes:
  data:
