version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
    volumes:
      - ./db:/var/lib/postgresql/data
  client:
    image: "node:10"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./client/:/home/node/app
    ports:
      - "8002:3000"
    command: bash -c "npm i && npm start"
  server:
    build: ./server/
    user: "node:10"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./server/:/home/node/app
    ports:
      - "8003:3000"
    command: bash -c "npm i && nodemon ./ --config ./nodeamon.json"
    depends_on:
      - db
