version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ""
    volumes:
      - ./db:/var/lib/postgresql/data
  web:
    build: ./
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "nodemon ./"
    depends_on:
      - db