version: '3'

services:
  db:
    image: postgres
  web:
    image: node:9-alpine
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "3000:3000"
    command: "yarn install && node ."
    depends_on:
      - db